application: advanced-search-demo
version: 1
runtime: python
api_version: 1

builtins:
- appstats: on
- datastore_admin: on
- deferred: on

handlers:
- url: /admin(/.*)?
  script: main.py
  login: admin

- url: /.*
  script: main.py
